### ISSUE TITLE
cannot actually snapcraft the project 

### ISSUE THREAD

**Issue by astroteo** [ericoporto/pyqthelloworld#1]
did you had been able to snpacraft this app ??

**Comment by ericoporto** [comment]
I think I was at the time , but looking now I think some plugs may be missing.

Can you show me what error messages are you getting and when?

**Comment by astroteo** [comment]
when i try to build the snap, with the current snapcraft.yaml i got this error:

Sorry, an error occurred in Snapcraft:
Traceback (most recent call last):
  File "/usr/bin/snapcraft", line 9, in <module>
    load_entry_point('snapcraft==2.43.1', 'console_scripts', 'snapcraft')()
  File "/usr/lib/python3/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1037, in invoke
    return Command.invoke(self, ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3/dist-packages/snapcraft/cli/_runner.py", line 93, in run
    ctx.forward(lifecyclecli.commands["snap"])
  File "/usr/lib/python3/dist-packages/click/core.py", line 552, in forward
    return self.invoke(cmd, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/snapcraft/cli/lifecycle.py", line 136, in snap
    project = _execute(steps.PRIME, parts=[], **kwargs)
  File "/usr/lib/python3/dist-packages/snapcraft/cli/lifecycle.py", line 35, in _execute
    lifecycle.execute(step, project_config, parts)
  File "/usr/lib/python3/dist-packages/snapcraft/internal/lifecycle/_runner.py", line 90, in execute
    executor.run(step, part_names)
  File "/usr/lib/python3/dist-packages/snapcraft/internal/lifecycle/_runner.py", line 196, in run
    self._create_meta(step, processed_part_names)
  File "/usr/lib/python3/dist-packages/snapcraft/internal/lifecycle/_runner.py", line 359, in _create_meta
    self.config.validator.schema,
  File "/usr/lib/python3/dist-packages/snapcraft/internal/meta/_snap_packaging.py", line 109, in create_snap_packaging
    packaging.write_snap_yaml()
  File "/usr/lib/python3/dist-packages/snapcraft/internal/meta/_snap_packaging.py", line 312, in write_snap_yaml
    snap_yaml = self._compose_snap_yaml()
  File "/usr/lib/python3/dist-packages/snapcraft/internal/meta/_snap_packaging.py", line 468, in _compose_snap_yaml
    snap_yaml["apps"] = self._wrap_apps(self._config_data["apps"])
  File "/usr/lib/python3/dist-packages/snapcraft/internal/meta/_snap_packaging.py", line 567, in _wrap_apps
    self._wrap_app(app, apps[app])
  File "/usr/lib/python3/dist-packages/snapcraft/internal/meta/_snap_packaging.py", line 575, in _wrap_app
    app[k] = self._wrap_exe(app[k], "{}-{}".format(k, name))
  File "/usr/lib/python3/dist-packages/snapcraft/internal/meta/_snap_packaging.py", line 546, in _wrap_exe
    with open(exepath, "rb") as exefile:
FileNotFoundError: [Errno 2] No such file or directory: '/home/teo/Dropbox/QT_Db/PyQT/pyqthelloworld/prime/bin/pyqthelloworld-wrapper'
We would appreciate it if you created a bug report at
https://launchpad.net/snapcraft/+filebug with the above text included.


....so i modififed  the  snapcraft.yaml as follow:

name: pyqthelloworld
version: 0.1.0
summary: pyqt hello world
description: |
 a pyqt5 python!!!! hello world test

grade: devel
confinement: strict

apps:
  pyqthelloworld:
    command: pyqthelloworld
    plugs: [home, unity7, x11, opengl, pulseaudio, wayland]

parts:
  pyqthelloworld:
    plugin: python

    stage-packages:
      - python-pyqt5
      - libc-bin
      - locales
    after: [desktop-qt5]




..doing like this i can generate and install the snap(sudo snap install pyqthelloworld0.1.0_amd64  --dangerous), but build when i run ( pyqthelloworld) i got this error:
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted (core dumped)

...any help would be really appreciated

**Comment by ericoporto** [comment]
Hey! I am sorry, I had to catch up on a lot of things and my local lxd is giving me some weird output, so I wasn't able to `snapcraft cleanbuild`. I updated the  [`snapcraft.yaml`](https://github.com/ericoporto/pyqthelloworld/blob/master/snap/snapcraft.yaml), [maybe](https://travis-ci.com/ericoporto/pyqthelloworld/jobs/152872616) it`s working? (it's slow and appears to hang when priming, but it eventually is building ok) I will only have time to check this carefully on either tomorrow night or the weekend though :/

**Comment by ericoporto** [comment]
@astroteo when you can, please tell me if it worked.

**Comment by ericoporto** [comment]
@astroteo  Hey!  my local lxd is giving me some weird output, so I wasn't able to `snapcraft cleanbuild`. I updated the  [`snapcraft.yaml`](https://github.com/ericoporto/pyqthelloworld/blob/master/snap/snapcraft.yaml), [maybe](https://travis-ci.com/ericoporto/pyqthelloworld/jobs/152872616) it`s working? (it's slow and appears to hang when priming, but it eventually is building ok) I will only have time to check this carefully on either tomorrow night or the weekend though :/
